#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

$composerAutoload = [
    __DIR__ . '/vendor/autoload.php', // in yii2-dev repo
    __DIR__ . '/../autoload.php', // installed as a composer binary
];
$vendorPath = null;
foreach ($composerAutoload as $autoload) {
    if (file_exists($autoload)) {
        require($autoload);
        $vendorPath = dirname($autoload);
        break;
    }
}


require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

Yii::setAlias('@solbianca/fias', dirname(__DIR__));

$application = new yii\console\Application([
    'id' => 'yii-console',
    'basePath' => __DIR__ . '/console',
    'controllerNamespace' => 'yii\console\controllers',
    'controllerMap' => [
        'fias' => [
            'class' => 'solbianca\fias\console\controllers\FiasController'
        ]
    ],
    'modules' => [
        'fias' => [
            'class' => 'solbianca\fias\Module',
        ],
    ],
    'components' => [
        'db' => [
            'class' => '\yii\db\Connection',
            'dsn' => 'mysql:host=127.0.0.1;dbname=fias',
            'username' => 'yhristenko',
            'password' => 'yhristenko',
            'charset' => 'utf8',
            'attributes' => [
              // use a smaller connection timeout
              PDO::ATTR_TIMEOUT => 10,
              PDO::MYSQL_ATTR_LOCAL_INFILE => true,
          ],
        ],
    ]

]);
if ($vendorPath !== null) {
    $application->setVendorPath($vendorPath);
}
$exitCode = $application->run();
exit($exitCode);
